import Link from 'next/link'
import './globals.css'

export const metadata = {
  title: 'Web tutorials',
  description: 'Generated by ChoYouJin',
}

// eslint-disable-next-line @next/next/no-async-client-component
export default async function RootLayout({ children }) {
  
  const res = await fetch('http://localhost:9999/topics/', {cache: 'no-cache'})
  const topics = await res.json()

  return (
    <html>
      <body>
        <h1><Link href='/'>WEB</Link></h1>
        <ol>
          {
          topics.map((item) => {
            return <li key={item.id}><Link href={`/read/${item.id}`}>{item.title}</Link></li>
          })
          }
        </ol>
          {children}
        <ul>
          <li><Link href='/create'>Create</Link></li>
          <li><Link href='/update/1'>Update</Link></li>
          <li><input type='button' value='delete' /></li>
        </ul>
      </body>
    </html>
  )
}
